# Created with komac v2.15.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: Microsoft.EventLogExpert
PackageVersion: 26.2.12.1177
Platform:
- Windows.Desktop
- Windows.Universal
MinimumOSVersion: 10.0.17763.0
InstallerType: msix
UpgradeBehavior: install
FileExtensions:
- evtx
PackageFamilyName: EventLogExpert_8wekyb3d8bbwe
RestrictedCapabilities:
- packageManagement
- runFullTrust
ReleaseDate: 2026-02-12
InstallationMetadata:
  DefaultInstallLocation: '%ProgramFiles%/WindowsApps/EventLogExpert_26.2.12.1177_x64__8wekyb3d8bbwe'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/microsoft/EventLogExpert/releases/download/v26.2.12.1177/EventLogExpert_26.2.12.1177_x64.msix
  InstallerSha256: 497A89206E34F837C2261BD7B59838F228281CF2486DF77341E1C83415DFB30B
  SignatureSha256: 18D6569EFB7B306B91D43E6C45A443A7AFE2C1919A63470C56B62B3AFC59A919
ManifestType: installer
ManifestVersion: 1.12.0
