# Created with komac v2.8.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.ConfigMgr.UploadOfflineFeedback
PackageVersion: 5.0.9128.1007
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: UploadOfflineFeedback.exe
UpgradeBehavior: install
ReleaseDate: 2025-04-17
Installers:
- Architecture: x86
  InstallerUrl: https://wingetselfhost.blob.core.windows.net/install/Microsoft.ConfigMgr.UploadOfflineFeedback/Microsoft.ConfigMgr.UploadOfflineFeedback.zip
  InstallerSha256: F738688DA9F1B15DC0C1852E46ACD96DF0B1122314A14B731C3180304EEB1DBD
ManifestType: installer
ManifestVersion: 1.9.0
