# Created with komac v2.11.2
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: Microsoft.eDiscoveryExportTool
PackageVersion: 15.20.1771.0
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: microsoft.office.client.discovery.unifiedexporttool.exe
UpgradeBehavior: install
Installers:
- Architecture: x86
  InstallerUrl: https://wingetselfhost.blob.core.windows.net/install/Microsoft.eDiscoveryExportTool/Microsoft.Office.Client.Discovery.UnifiedExportTool.zip
  InstallerSha256: 66C5E4C8EF975CDD0775D343AB3C1A5551C903ABBCB26415B13C73BB48BAF8F7
ManifestType: installer
ManifestVersion: 1.9.0
