blank_issues_enabled: true
contact_links:
  - name: WinGet Client issues
    url: https://github.com/microsoft/winget-cli/issues
    about: Please create issues related to the WinGet Client here.
  - name: Review open issues
    url: https://github.com/microsoft/winget-pkgs/issues
    about: Please check if your issue isn't already there.
