# Created with komac v2.14.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: Microsoft.DeploymentToolkit
PackageVersion: 6.3.8450.1000
InstallerLocale: en-US
InstallerType: wix
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2026-01-14
ElevationRequirement: elevatesSelf
Installers:
- Architecture: x86
  InstallerUrl: https://wingetselfhost.blob.core.windows.net/install/Microsoft.DeploymentToolkit/6.3.8450.1000/MicrosoftDeploymentToolkit_x86.msi
  InstallerSha256: 22429089718FB2BC92DCAE0B095C389025B5F7735FDE9198EC6F248E7A626F3A
  ProductCode: '{71890CC3-4BDD-4CF6-A0B2-EA9316F9E73C}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Deployment Toolkit (6.3.8450.1000)
    ProductCode: '{71890CC3-4BDD-4CF6-A0B2-EA9316F9E73C}'
    UpgradeCode: '{42D9191C-0C0E-45E5-BB94-2DF35BB6C10C}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles(x86)%\Microsoft Deployment Toolkit'
- Architecture: x64
  InstallerUrl: https://wingetselfhost.blob.core.windows.net/install/Microsoft.DeploymentToolkit/6.3.8450.1000/MicrosoftDeploymentToolkit_x64.msi
  InstallerSha256: E73823DB601B06E9C222AE816BBDDD491ECB823A1F8CCE0F73EEC9DE51C1690E
  ProductCode: '{38D2CBE2-862C-4C39-8D65-A4C1C2220160}'
  AppsAndFeaturesEntries:
  - DisplayName: Microsoft Deployment Toolkit (6.3.8450.1000)
    ProductCode: '{38D2CBE2-862C-4C39-8D65-A4C1C2220160}'
    UpgradeCode: '{42D9191C-0C0E-45E5-BB94-2DF35BB6C10C}'
  InstallationMetadata:
    DefaultInstallLocation: '%ProgramFiles%\Microsoft Deployment Toolkit'
ManifestType: installer
ManifestVersion: 1.10.0
