# Created with komac v2.16.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: vinaypamnani.WMIExplorer
PackageVersion: 2.0.0.2
PackageLocale: en-US
Publisher: vinaypamnani
PublisherUrl: https://github.com/vinaypamnani
PublisherSupportUrl: https://github.com/vinaypamnani/wmie/issues
PackageName: WMI Explorer
PackageUrl: https://github.com/vinaypamnani/wmie
License: MIT
LicenseUrl: https://github.com/vinaypamnani/wmie2/blob/HEAD/LICENSE.md
ShortDescription: A modern Windows desktop application for exploring and managing Windows Management Instrumentation (WMI) namespaces, classes, instances, properties, and methods.
ReleaseNotes: |-
  Version 2.0.0.2 [10-05-2017]
  - Migration to GitHub.
  - Added option to specify COMPUTERNAME as a parameter and automatically connect.
    Example: WmiExplorer.exe COMPUTERNAME
ReleaseNotesUrl: https://github.com/vinaypamnani/wmie/releases/tag/v2026.01.05.01
ManifestType: defaultLocale
ManifestVersion: 1.12.0
