name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:

jobs:
  main:
    runs-on: windows-2025
    permissions:
      contents: write
      id-token: write
    environment: dev
    steps:
      - uses: actions/checkout@v5
      - name: Merge manifests
        run: |
          choco install yq

          $TMP_MANIFESTS = "$env:TEMP\manifests"
          New-Item -ItemType Directory -Path $TMP_MANIFESTS -Force
          
          $leafDirs = Get-ChildItem -Path "manifests" -Recurse -Directory | Where-Object { 
            (Get-ChildItem -Path $_.FullName -Filter "*.yaml").Count -gt 0 
          }
          
          foreach ($dir in $leafDirs) {
            $yamlFiles = Get-ChildItem -Path $dir.FullName -Filter "*.yaml" | Select-Object -ExpandProperty FullName
            
            if ($yamlFiles.Count -gt 0) {
              $packageId = $dir.Parent.Name
              $version = $dir.Name
              $outputFile = Join-Path -Path $TMP_MANIFESTS -ChildPath "$packageId-$version.yaml"
              
              # Start-Process and wildcards don't work
              & yq ea '. as $item ireduce ({}; . * $item )' $yamlFiles[0] $yamlFiles[1] $yamlFiles[2] > $outputFile
              & yq -i '.ManifestType = "merged"' $outputFile
              & yq -i '... comments=""' $outputFile
            }
          }
      
      - name: Setup and run IndexCreationTool
        run: |
            Invoke-WebRequest "${{ github.server_url }}/${{ github.repository }}/releases/latest/download/AppInstallerCLIE2ETests.zip" -OutFile ..\AppInstallerCLIE2ETests.zip
            Expand-Archive ..\AppInstallerCLIE2ETests.zip -DestinationPath ..\
            
            $version = Get-Date -Format yyyy.M.d.hm
            (Get-Content -Path package/AppxManifest.xml) -replace "<VERSION>", $version | Set-Content -Path package/AppxManifest.xml
            ..\AppInstallerCLIE2ETests\IndexCreationTool.exe -f source.json
            git restore package\AppxManifest.xml
        env:
          PFX_PASSWORD: ${{ secrets.PFX_PASSWORD }}

      - uses: azure/login@v2
        with:
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true
      # - name: Sign index
      #   uses: azure/trusted-signing-action@v0
      #   continue-on-error: true
      #   with:
      #     endpoint: ${{ vars.AZURE_SIGNING_ENDPOINT }}
      #     trusted-signing-account-name: ${{ vars.AZURE_SIGNING_ACCOUNT }}
      #     certificate-profile-name: ${{ vars.AZURE_SIGNING_PROFILE }}
      #     files-folder: cache
      #     files-folder-filter: msix
      #     exclude-environment-credential: true
      #     exclude-workload-identity-credential: true
      #     exclude-managed-identity-credential: true
      #     exclude-shared-token-cache-credential: true
      #     exclude-visual-studio-credential: true
      #     exclude-visual-studio-code-credential: true
      #     exclude-azure-cli-credential: false
      #     exclude-azure-powershell-credential: true
      #     exclude-azure-developer-cli-credential: true
      #     exclude-interactive-browser-credential: true
      - name: Upload to blob storage
        run: az storage blob upload-batch --source cache --destination cache --account-name wingetselfhost --auth-mode login --overwrite

      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: "chore: regenerate cache"
          pull: "--rebase --autostash"
