name: main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  main:
    runs-on: windows-2025
    permissions:
      contents: write
      id-token: write
    environment: dev
    steps:
      - uses: actions/checkout@v4
      - name: Setup and run IndexCreationTool
        continue-on-error: true
        run: |
          Invoke-WebRequest "${{ github.server_url }}/${{ github.repository }}/releases/latest/download/AppInstallerCLIE2ETests.zip" -OutFile AppInstallerCLIE2ETests.zip
          Expand-Archive AppInstallerCLIE2ETests.zip -DestinationPath ..\AppInstallerCLIE2ETests
          ..\AppInstallerCLIE2ETests\IndexCreationTool.exe -f source.json
      - name: Sign index
        uses: azure/trusted-signing-action@v0
        with:
          endpoint: ${{ vars.AZURE_SIGNING_ENDPOINT }}
          trusted-signing-account-name: ${{ vars.AZURE_SIGNING_ACCOUNT }}
          certificate-profile-name: ${{ vars.AZURE_SIGNING_PROFILE }}
          files-folder: cache
          files-folder-filter: msix
          # azure-tenant-id: ${{ vars.AZURE_TENANT_ID }}
          # azure-client-id: ${{ vars.AZURE_CLIENT_ID }}
          # azure-client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
      - uses: EndBug/add-and-commit@v9.1.4
        with:
          default_author: github_actions
          message: "chore: regenerate cache"
          pull: "--rebase --autostash"
