name: update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0/4 * * *

jobs:
  update:
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    outputs:
      updated: ${{ steps.commit.outputs.pushed }}
    strategy:
      fail-fast: false
      matrix:
        # TODO automatically try different architectures?
        # https://github.com/zodiacon
        # okta
        # pending .tar.gz: ipatool, buildkit, containerd, AsciinemaTrim
        # pending ClickOnce: Microsoft.Kusto.Explorer, Microsoft.eDiscoveryExportTool
        include:
          # needs partial URL matching
          # - id: NationalSecurityAgency.Ghidra
          #   repo: NationalSecurityAgency/ghidra
          #   url: https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_{VERSION}_build/ghidra_{VERSION}_PUBLIC_{DATE}.zip
          # needs prerelease matching, I think one of the forks supports this
          # - id: ralish.CertUiExts
          #   repo: ralish/CertUiExts
          #   url: https://github.com/ralish/CertUiExts/releases/download/v{VERSION}/CertUiExts-v{VERSION}-x64.zip https://github.com/ralish/CertUiExts/releases/download/v{VERSION}/CertUiExts-v{VERSION}-x86.zip
          - id: Microsoft.Azure.BatchExplorer
            repo: Azure/BatchExplorer
            url: https://github.com/Azure/BatchExplorer/releases/download/v{VERSION}/BatchExplorer.Setup.{VERSION}.exe
          - id: PavelYosifovich.ProcMonX
            repo: zodiacon/ProcMonXv2
            url: https://github.com/zodiacon/ProcMonXv2/releases/download/{VERSION}/ProcMonX.exe
          - id: Microsoft.EventLogExpert
            repo: microsoft/EventLogExpert
            url: https://github.com/microsoft/EventLogExpert/releases/download/v{VERSION}/EventLogExpert_{VERSION}_x64.msix
          - id: WildByDesign.WDACTrayTool
            repo: WildByDesign/WDACTrayTool
            url: https://github.com/WildByDesign/WDACTrayTool/releases/download/{VERSION}/AppControlTray-{VERSION}.zip
          - id: vinaypamnani.WMIExplorer
            repo: vinaypamnani/wmie2
            url: https://github.com/vinaypamnani/wmie2/releases/download/v{VERSION}/WmiExplorer_{VERSION}.zip
    steps:
      - uses: actions/checkout@v6
      - name: Setup Komac
        run: |
          wget https://github.com/pl4nty/Komac/releases/download/nightly/komac-nightly-x86_64-unknown-linux-gnu.tar.gz && tar -xzf komac-nightly-x86_64-unknown-linux-gnu.tar.gz
          chmod +x komac
          mkdir -p /home/runner/.local/bin
          sudo mv komac /home/runner/.local/bin/komac
          rm komac-nightly-x86_64-unknown-linux-gnu.tar.gz
          rm LICENSE.md

      # https://github.com/michidk/winget-updater/blob/main/action.yml
      - name: Detect latest release
        id: latest_release
        uses: actions/github-script@v8
        with:
          script: |
            const [owner, repo] = '${{ matrix.repo }}'.split('/');
            try {
              const { data } = await github.rest.repos.getLatestRelease({ owner, repo });
              const tagName = data.tag_name.startsWith('v') ? data.tag_name.substring(1) : data.tag_name;
              return tagName;
            } catch (error) {
              core.setFailed(`Failed to get latest release for repo: ${owner}/${repo}`);
              process.exit(1);
            }
      - name: Compose URL
        shell: bash
        run: |
          VERSION=${{ steps.latest_release.outputs.result }}
          URL=${{ matrix.url }}
          FINAL_URL=$(echo $URL | sed "s/{VERSION}/$VERSION/g")
          echo "FINAL_URL=$FINAL_URL" >> $GITHUB_ENV
          echo "Detected latest Version: ${{ steps.latest_release.outputs.result }}"
          echo "Final URL: $FINAL_URL"
      - name: Run Komac
        shell: 'script -q -e -a /dev/null -c "bash {0}"'
        continue-on-error: true
        run: /home/runner/.local/bin/komac update ${{ matrix.id }} --version ${{ steps.latest_release.outputs.result }} --urls $FINAL_URL --output . --dry-run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: EndBug/add-and-commit@v9.1.4
        id: commit
        with:
          default_author: github_actions
          message: "chore: update ${{ matrix.id }} to ${{ steps.latest_release.outputs.result }}"
          pull: "--rebase --autostash"

  main:
    uses: ./.github/workflows/main.yml
    needs: update
    if: needs.update.outputs.updated == 'true'
    permissions:
      contents: write
      id-token: write
