name: Update Packages

on:
  workflow_dispatch:
  schedule:
    - cron: 23 */4 * * *

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update-packages:
    name: Update Packages
    runs-on: ubuntu-26.04-arm
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Environment
        uses: jdx/mise-action@e6a8b3978addb5a52f2b4cd9d91eafa7f0ab959d # v4.2.0
        with:
          version: 2026.7.7
          install_args: bun

      - name: Install Dependencies
        run: bun ci --production

      - uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ vars.GH_CLIENT_ID }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write

      - name: Update Packages
        run: bun start
        env:
          KOMAC_FORK_OWNER: ${{ github.repository_owner }}
          KOMAC_GITHUB_OWNER: ${{ github.repository_owner }}
          KOMAC_GITHUB_REPO: ${{ github.event.repository.name }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
